#!/bin/bash

# Trap any error and print the error message with the line number
trap 'echo "Error occurred at line $LINENO"; exit 1' ERR

# Change to the home directory
cd ~

# update your system
sudo pacman -Syu || { echo "System update failed."; exit 1; }

# Install Hyprland
sudo pacman -S hyprland wofi dolphin vim firefox alacritty waybar pulseaudio pipewire wireplumber xdg-desktop-portal-hyprland pavucontrol grim slurp wl-clipboard unzip || { echo "Package installation failed."; exit 1; }

# Install yay
if ! command -v yay &> /dev/null; then
    echo "yay could not be found, installing yay..."
    git clone https://aur.archlinux.org/yay.git
    pushd yay
    makepkg -si || { echo "Failed to build/install yay."; exit 1; }
    popd
else
    echo "yay is already installed."
fi

# Install wlogout and brave in yay
yay -S wlogout brave-bin || { echo "Failed to install AUR packages."; exit 1; }

# configure wofi, alacritty, wlogout and waybar
mv Hyprland-Configs/configs/wofi ~/.config
mv Hyprland-Configs/configs/alacritty.toml ~/.config
mv Hyprland-Configs/configs/waybar ~/.config
mv Hyprland-Configs/configs/wlogout ~/.config

# installing Fonts
sudo pacman -S noto-fonts noto-fonts-emoji noto-fonts noto-fonts-cjk ttf-font-awesome

# configure hyprland.conf
cp Hyprland-Configs/configs/hypr/hyprland.conf ~/.config/hypr/hyprland.conf

# install Hyprpaper
sudo pacman -S hyprpaper

# configure wallpaper path
sudo mkdir -p /usr/share/wallpaper
sudo cp Hyprland-Configs/Wallpapers/* /usr/share/wallpaper/

# Setting up wallpaper
touch ~/.config/hypr/hyprpaper.conf
cp Hyprland-Configs/configs/hypr/hyprpaper.conf ~/.config/hypr/hyprpaper.conf

# minimal vim
touch .vimrc
cp Hyprland-Configs/configs/.vimrc .vimrc

# LightDM
sudo pacman -S lightdm lightdm-slick-greeter || { echo "Failed to install LightDM."; exit 1; }
sudo systemctl enable lightdm.service
sudo mv Hyprland-Configs/configs/Lighdm/slick-greeter.conf /etc/lightdm/slick-greeter.conf
sudo cp Hyprland-Configs/configs/Lighdm/lightdm.conf /etc/lightdm/lightdm.conf

# Reboot
read -p "Setup complete. Do you want to reboot now? (y/n): " REBOOT
if [[ $REBOOT =~ ^[Yy]$ ]]; then
    reboot
else
    echo "Reboot skipped. Please reboot manually to apply changes."
fi