#!/bin/bash

# update your system
sudo pacman -Syu

# Install Hyprland
sudo pacman -S hyprland wofi dolphin vim firefox alacritty waybar pulseaudio pipewire wireplumber xdg-desktop-portal-hyprland pavucontrol grim slurp wl-clipboard unzip lightdm

# Install yay
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

# Install wlogout and brave in yay
yay -S wlogout
yay -S brave-bin

# configure wofi, alacritty, wlogout and waybar
mv Hyprland-Configs/configs/wofi ~/.config
mv Hyprland-Configs/configs/alacritty.toml ~/.config
mv Hyprland-Configs/configs/waybar ~/.config
mv Hyprland-Configs/configs/wlogout ~/.config
sudo pacman -S noto-fonts noto-fonts-emoji noto-fonts noto-fonts-cjk ttf-font-awesome

# configure hyprland.conf
cp Hyprland-Configs/configs/hypr/hyprland.conf ~/.config/hypr/hyprland.conf

# install Hyprpaper
sudo pacman -S hyprpaper

# configure wallpaper path
sudo mkdir /usr/share/wallpaper
sudo cp Hyprland-Configs/Wallpapers/* /usr/share/wallpaper/

# Setting up wallpaper
touch ~/.config/hypr/hyprpaper.conf
cp Hyprland-Configs/configs/hypr/hyprpaper.conf ~/.config/hypr/hyprpaper.conf

# minimal vim
touch .vimrc
cp Hyprland-Configs/configs/.vimrc .vimrc

# LightDM
sudo pacman -S lightdm
sudo systemctl enable lightdm.service
sudo pacman -S lightdm-slick-greeter
sudo mv Hyprland-Configs/configs/Lighdm/slick-greeter.conf /etc/lightdm/slick-greeter.conf
sudo cp Hyprland-Configs/configs/Lighdm/lightdm.conf /etc/lightdm/lightdm.conf

reboot
exit